#!/usr/bin/env make -f

###############################################################################@
#
# @BEGIN
#
# @COPYRIGHT BEGIN
# Copyright (C) 2020 Panos I. Papadopoulos <panos1962_AT_gmail_DOT_com>
# @COPYRIGHT END
#
# @FILETYPE BEGIN
# makefile
# @FILETYPE END
#
# @FILE BEGIN
# www/Makefile —— makefile αρχικής σελίδας εφαρμογής "anamoni"
# @FILE END
#
# @HISTORY BEGIN
# Created: 2020-09-12
# @HISTORY END
#
# @END
#
###############################################################################@

all:
	:
